### PR TITLE
windows

### PR DESCRIPTION
**Pull request by mrzl**
hey there, 

ive been testing this on windows and needed to adjust something tiny. additionally ive added the 64bit release library of dlib that ive built on windows 10. 

yours,
marcel

### CODE REVIEW

**Comment by HalfdanJ** [comment]
Awesome, thanks!

**Comment by HalfdanJ** [comment]
Hi @mrzl, do you by any chance remember what command you ran to compile for windows? I'd like to update the project to DLIB 19.7, but since the windows build hasn't been added to the apothecary build script, I'm not able to make sure I build it the correct way (I'm not a windows user, so doing it a bit in blind)

**Comment by mrzl** [comment]
hey @HalfdanJ not really, but i remember it being simple and quick.. i could do it again and write it up in case i stumble upon some not-no-simple things? you need dlib 19.7 for win10 for 64bits only right?

**Comment by HalfdanJ** [comment]
I want to update the headers to 19.7, so just need the windows lib to follow that. Would be very helpful if you could run it at some point

**Pull request merged**
